apiVersion: v1
kind: Service
metadata:
  name: balance-service
  labels:
    app: balance-service
spec:
  selector:
    tier: balance
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.balanceService.port }}
  type: ClusterIP