apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-metrics-monitor
  labels:
    app: user-metrics-monitor
spec:
  endpoints:
    - port: user-metrics
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: user-service