userService:
  replicaCount: 3
  port: 8000

balanceService:
  replicaCount: 2
  port: 8000

postgresql:
  auth:
    database: app
    postgresPassword: changeme

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: { }

ingress-nginx:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: prometheus
        enabled: true

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
  config:
    datasource:
      host: app-postgresql
      database: app
      user: postgres
      password: changeme