apiVersion: v1
data:
  dbUrl: jdbc:postgresql://{{ .Release.Name}}-postgresql:5432/{{ .Values.postgresql.auth.database }}?useSSL=false
  dbName: {{ .Values.postgresql.auth.database }}
  dbUser: postgres
kind: ConfigMap
metadata:
  name: app-config-map