apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-claim0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.folder }}