apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels:
    app: kuber-service
spec:
  selector:
    env: prod
  ports:
    - protocol: TCP
      name: metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP